export const schemas = {
    clientes: {
        id: { label: 'Código Cliente', type: 'text', required: true, readonlyOnEdit: true },
        descripcion: { label: 'Razón Social', type: 'text', required: true },
        email: { label: 'Email', type: 'email' },
        logoUrl: { label: 'URL del Logo', type: 'text' },
    },
    productos: {
        id: { label: 'Número de Pieza', type: 'text', required: true, readonlyOnEdit: true },
        descripcion: { label: 'Descripción', type: 'text', required: true },
        imageUrl: { label: 'URL de Imagen', type: 'text' },
        clienteId: { label: 'Cliente', type: 'relation', collection: 'clientes', required: true },
        proyectoId: { label: 'Proyecto', type: 'relation', collection: 'proyectos' },
        version: { label: 'Versión', type: 'text' },
        piezasPorVehiculo: { label: 'Piezas por Vehículo', type: 'number' },
        site: { label: 'LC Site / KD', type: 'select', options: ['BARACK', 'KD'] },
        aspecto: { label: 'Aspecto (Y/N)', type: 'boolean' },
        isActivo: { label: 'Activo', type: 'boolean' },
        formattingRules: [{ key: 'isActivo', operator: 'equals', value: false, class: 'bg-red-50 text-red-900 hover:bg-red-100' }]
    },
    insumos: {
        id: { label: 'Número de Pieza', type: 'text', required: true, readonlyOnEdit: true },
        descripcion: { label: 'Descripción', type: 'text', required: true },
        imageUrl: { label: 'URL de Imagen', type: 'text' },
        proveedorId: { label: 'Proveedor', type: 'relation', collection: 'proveedores' },
        materialComponente: { label: 'Material del Componente', type: 'text' },
        color: { label: 'Color', type: 'text' },
        materiaPrimaBase: { label: 'Materia Prima Base', type: 'text' },
        proveedorMateriaPrimaId: { label: 'Proveedor Materia Prima', type: 'relation', collection: 'proveedores' },
        unidadMedidaId: { label: 'Unidad', type: 'relation', collection: 'unidades', field: 'id' },
    },
    subproductos: {
        id: { label: 'Número de Pieza', type: 'text', required: true, readonlyOnEdit: true },
        descripcion: { label: 'Descripción', type: 'text', required: true },
        imageUrl: { label: 'URL de Imagen', type: 'text' },
        procesoId: { label: 'Proceso', type: 'relation', collection: 'procesos' },
        materialComponente: { label: 'Material del Componente', type: 'text' },
        color: { label: 'Color', type: 'text' },
        materiaPrimaBase: { label: 'Materia Prima Base', type: 'text' },
        proveedorMateriaPrimaId: { label: 'Proveedor Materia Prima', type: 'relation', collection: 'proveedores' },
        unidadMedidaId: { label: 'Unidad', type: 'relation', collection: 'unidades', field: 'id' },
    },
    proveedores: {
        id: { label: 'Código Proveedor', type: 'text', required: true, readonlyOnEdit: true },
        descripcion: { label: 'Razón Social', type: 'text', required: true },
        contacto: { label: 'Contacto', type: 'text' },
        telefono: { label: 'Teléfono', type: 'text' },
    },
    unidades: {
        id: { label: 'Unidad', type: 'text', required: true, readonlyOnEdit: true },
        descripcion: { label: 'Descripción', type: 'text' },
    },
    procesos: {
        id: { label: 'Código Proceso', type: 'text', required: true, readonlyOnEdit: true },
        descripcion: { label: 'Descripción', type: 'text', required: true },
    },
    proyectos: {
        id: { label: 'Código Proyecto', type: 'text', required: true, readonlyOnEdit: true },
        descripcion: { label: 'Descripción', type: 'text', required: true },
        fechaEmision: { label: 'Fecha de Emisión', type: 'date' },
        fechaRevision: { label: 'Fecha de Revisión', type: 'date' },
        revision: { label: 'Revisión', type: 'text' },
        autor: { label: 'Autor', type: 'text' },
        realizo: { label: 'Realizó', type: 'text' },
    },
    default: {
        id: { label: 'ID', type: 'text', required: true, readonlyOnEdit: true },
        descripcion: { label: 'Descripción', type: 'text' },
    }
};
